#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from __future__ import annotations

import json
from pathlib import Path

import yaml


DOCKER_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = DOCKER_DIR.parent
CONFIG_DIR = PROJECT_ROOT / "config"
OUTPUT_PATH = DOCKER_DIR / ".generated.env"


def read_yaml(name: str) -> dict:
    path = CONFIG_DIR / name
    with path.open("r", encoding="utf-8") as handle:
        return yaml.safe_load(handle) or {}


def read_json(name: str) -> dict:
    path = CONFIG_DIR / name
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def proxy_routes(proxy_cfg: dict, proxy_state: dict) -> dict:
    state_routes = proxy_state.get("routes")
    if isinstance(state_routes, dict) and state_routes:
        return state_routes

    active_state = proxy_state.get("active_state", "default")
    states = proxy_cfg.get("states", {})
    active = states.get(active_state, states.get("default", {}))
    return active.get("routes", {})


def main() -> None:
    auth_cfg = read_yaml("authserver.yaml")
    world_cfg = read_yaml("worldserver.yaml")
    proxy_cfg = read_json("proxy.json")
    proxy_state = read_json("proxy.state.json")

    routes = proxy_routes(proxy_cfg, proxy_state)
    telnet_cfg = proxy_cfg.get("shared", {}).get("telnet", {})

    values = {
        "AUTH_PORT": int(auth_cfg.get("authserver", {}).get("port", 3720)),
        "WORLD_PORT": int(world_cfg.get("worldserver", {}).get("port", 8086)),
        "PROXY_AUTH_PORT": int(routes.get("auth", {}).get("listen", 3724)),
        "PROXY_WORLD_PORT": int(routes.get("world", {}).get("listen", 8085)),
        "PROXY_TELNET_PORT": int(telnet_cfg.get("port", 1337)),
        "DBC_CONTAINER_PATH": str(world_cfg.get("dbc_path", "/app/data/client/dbc")),
        "DB2_CONTAINER_PATH": str(world_cfg.get("db2_path", "/app/data/client/db2")),
        "MAPS_CONTAINER_PATH": str(world_cfg.get("maps_path", "/app/data/client/maps")),
    }

    lines = [
        "# Generated by docker/generate-env.py from ../config.",
        "# Do not edit this file by hand.",
    ]
    lines.extend(f"{key}={value}" for key, value in values.items())
    OUTPUT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
