tool_name: BinaryPacketsDSL
author: Magnus Pettersson
version: 0.5.0
project_name: Mist of Pandaria 5.4.8

paths:
  root: .
  def_dir: data/def
  capture_dir: data/captures
  logs: logs

Logging:
  logging_levels: All
  logging_file_levels: All
  log_file: dsl.log
  log_file_unit_test: unit_test.log
  show_scope: false

  enGB: &enGB " [%Y-%m-%d %H:%M:%S]"
  en: &en " [%m/%d/%Y %I:%M:%S %p]"
  ru: &ru " [%d.%m.%Y %H:%M:%S]"
  se: &se " [%Y-%m-%d %H:%M:%S]"
  none: &none ""

  date_format: *se

database:
  host: 192.168.11.81
  port: 3306
  username: root
  password: pwd
  auth_db: skyfire548_auth
  world_db: skyfire548_world
  characters_db: skyfire548_characters
  # auth_db: pandaria548_auth
  # world_db: pandaria548_world
  # characters_db: pandaria548_characters

crypto:
  N: 894B645E89E1535BBDAD5B8B290650530801B18EBFBF5E8FAB3C82872A3E9BB7
  g: 7

dsl:
  write_to_log: true
  log_file: dsl.log
  show_scope: true
  logging_levels: "None"
  logging_file_levels: "Info, Debug, Trace, Warning, Error"
