tool_name: BinaryPacketsDSL
author: Magnus Pettersson
version: 0.5.0
project_name: Mist of Pandaria 5.4.8
paths:
  root: .
  def_dir: data/def
  capture_dir: data/proxy/captures
  json_dir: data/proxy/json
  debug_dir: data/proxy/debug
  logs: logs
Logging:
  logging_levels: All
  logging_file_levels: All
  log_file: dsl.log
  log_file_unit_test: unit_test.log
  show_scope: false
  enGB: ' [%Y-%m-%d %H:%M:%S]'
  en: ' [%m/%d/%Y %I:%M:%S %p]'
  se: ' [%Y-%m-%d %H:%M:%S]'
  none: ''
  date_format: ' [%Y-%m-%d %H:%M:%S]'
database:
  host: 192.168.11.81
  port: 3306
  username: root
  password: pwd
  auth_db: skyfire548_auth
  world_db: skyfire548_world
  characters_db: skyfire548_characters
worldserver:
  motd: Hello World
  preload_gameobjects: true
  preload_npcs: false
  weather_cycle_seconds: 600
World: null
Transport:
  ExperimentalPlayerCreateLivingMovement: false
  DebugLifecycle: false
  DebugPackets: false
  DebugMessages: false
  AutonomousVisibility: false
crypto:
  N: 894B645E89E1535BBDAD5B8B290650530801B18EBFBF5E8FAB3C82872A3E9BB7
  g: 7
dsl:
  write_to_log: true
  log_file: dsl.log
  show_scope: true
  logging_levels: None
  logging_file_levels: Info, Debug, Trace, Warning, Error
