Logging:
  # Specify the logging levels as names (comma-separated) or use "All" for all levels.
  # Levels:
  #   - None
  #   - Success
  #   - Information
  #   - Anticheat
  #   - Warning
  #   - Error
  #   - Debug
  #   - Script
  #   - All
  # Example:
  #  logging_levels: Information, Success, Debug, Script, Error
  #  logging_levels: All
  logging_levels: All
  logging_file_levels: All
  log_file: dsl.log
  log_file_unit_test: unit_test.log

  # Define the date format for log timestamps.
  # Examples of formats:
  # usage: date_format: *se
  enGB: &enGB " [%Y-%m-%d %H:%M:%S]"
  en: &en " [%m/%d/%Y %I:%M:%S %p]"
  se: &se " [%Y-%m-%d %H:%M:%S]"
  none: &none ""

  date_format: *se
