worldserver:
  host: 0.0.0.0
  port: 8086
  logging:
    write_to_log: true
    log_file: worldserver.log
  output:
    raw: true
    decode: true
    dsl_warnings: true
    blacklist: []

dbc_path: "data/client/dbc"
db2_path: "data/client/db2"
maps_path: "data/client/maps"

Transport:
  EnableElevators: true
  EnableMovingTransports: true
  DebugLifecycle: false
  DebugMovement: false
  DebugPackets: false
  DebugMessages: true
  AutonomousVisibility: true

Taxi:
  EnableFlightPaths: true
  DebugMovement: false

Player:
  EnableMapExploreCheat: false
  EnableTaxiCheat: false

World:
  EnableGameObjects: true
  DebugGameObjectOrientation: false
  EnableNPCs: true
  EnableNPCAutoStream: true

Api:
  EnableServer: true
  EnableBridge: true
  Host: 0.0.0.0
  Port: 8090
  Token: ""
